name: Waka Readme

on:
  schedule:
    # 北京时间00:00
    - cron: '0 16,4 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_76fdcae5-8e33-4a6b-ab86-84c10f462550 }}
          GH_TOKEN: ${{ secrets.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 }}
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_UPDATED_DATE: "False"
